# numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.
File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np


#### 2. Create a null vector of size 10 (★☆☆)

In [4]:
np.zeros((10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [5]:
np.array([int(x==5) for x in range(10)])

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)

In [6]:
np.arange(10,49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

0 to 8 is not possible

In [7]:
a= np.arange(0,9).reshape(3,3)
b=np.arange(0,18,2).reshape(3,3)

In [8]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

#### 7. Create a 3x3 identity matrix (★☆☆)

In [11]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 8. Create a 3x3x3 array with random values (★☆☆)

In [12]:
np.random.random(((3,3,3)))

array([[[0.4163431 , 0.1970816 , 0.05459896],
        [0.44509548, 0.25510425, 0.19712357],
        [0.30880886, 0.98493524, 0.07880585]],

       [[0.74495969, 0.89414606, 0.82231446],
        [0.11454349, 0.49283682, 0.30446253],
        [0.58134039, 0.6819604 , 0.36390845]],

       [[0.24029977, 0.71434904, 0.22177235],
        [0.02210794, 0.78854221, 0.33117381],
        [0.54121718, 0.9520349 , 0.28937225]]])

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
array=np.random.random((10,10))

In [14]:
array

array([[0.61846229, 0.46710309, 0.78608147, 0.67377359, 0.24341938,
        0.21679413, 0.42305527, 0.13185161, 0.26463285, 0.06433251],
       [0.4489492 , 0.90227348, 0.36410055, 0.85387651, 0.35311518,
        0.59262153, 0.39453344, 0.25874659, 0.10659874, 0.26965931],
       [0.46163215, 0.28714151, 0.12878789, 0.29645815, 0.67025288,
        0.3361551 , 0.1936323 , 0.28901326, 0.60826864, 0.92192921],
       [0.52091793, 0.03737422, 0.70710251, 0.58501471, 0.81281251,
        0.73168146, 0.62033994, 0.11990085, 0.02051379, 0.19744952],
       [0.30591364, 0.8549447 , 0.62027352, 0.5052824 , 0.92969713,
        0.3749675 , 0.54208427, 0.98362984, 0.13786714, 0.0637785 ],
       [0.39705747, 0.66115831, 0.61204988, 0.45751037, 0.8674553 ,
        0.67504253, 0.95864688, 0.78528419, 0.36113718, 0.17888471],
       [0.60006349, 0.37334406, 0.50809667, 0.07584315, 0.35133189,
        0.42736474, 0.57950221, 0.69883153, 0.30052376, 0.31875011],
       [0.82090144, 0.17069371, 0.5865715

In [15]:
np.min(array)

0.0020731940476371724

In [16]:
np.max(array)

0.9906992202197507

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)

In [17]:
a=np.arange(30)

In [18]:
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [19]:
np.mean(a)

14.5

#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [20]:
np.diag([1, 2, 3, 4, 5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

#### 12. Normalize a 5x5 random matrix (★☆☆)


In [21]:
z=np.random.random((5,5))
print("Before normalize")
print(z)
d=(z - np.mean(z))/np.std(z)
print("After normalize")
print(d)

Before normalize
[[0.71742045 0.51393697 0.08618295 0.32215538 0.1048347 ]
 [0.25999954 0.12773476 0.5895708  0.42667145 0.27294757]
 [0.6075871  0.63460002 0.22574123 0.46113452 0.96114461]
 [0.19447615 0.06825982 0.46862024 0.76815801 0.68728744]
 [0.29781425 0.04485556 0.62783426 0.95459661 0.90930989]]
After normalize
[[ 0.94359477  0.21658997 -1.31168747 -0.46860634 -1.24504859]
 [-0.69067643 -1.16323137  0.48681417 -0.09519185 -0.64441576]
 [ 0.55118271  0.64769434 -0.81307432  0.02793763  1.81437121]
 [-0.92477807 -1.37572314  0.05468259  1.12486964  0.83593567]
 [-0.55557221 -1.45934176  0.62352165  1.79097657  1.62917639]]


#### 13. How to find common values between two arrays? (★☆☆)

In [22]:
print(a)
print(b)
print("the comman values are:")
np.intersect1d(a,b) 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
the comman values are:


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

#### 14. Create a random vector of size 10 and sort it (★★☆)

In [23]:
c=np.random.random(10)
print(c)
print("That was normal vector")
c.sort()
print(c)
print("This is sorted vector")

[0.76097612 0.12988451 0.69181056 0.91240755 0.61798149 0.87536826
 0.28003662 0.88378432 0.00204294 0.00496825]
That was normal vector
[0.00204294 0.00496825 0.12988451 0.28003662 0.61798149 0.69181056
 0.76097612 0.87536826 0.88378432 0.91240755]
This is sorted vector



#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [24]:
d=np.random.random(10)
print('the random array is:')
print(d)
d[d.argmax()] = 0
print("the max value is replaced by 0:")
print(d)

the random array is:
[0.03337902 0.42313139 0.96502577 0.7883864  0.65559369 0.59890064
 0.63134627 0.36234026 0.86503295 0.32321607]
the max value is replaced by 0:
[0.03337902 0.42313139 0.         0.7883864  0.65559369 0.59890064
 0.63134627 0.36234026 0.86503295 0.32321607]


In [25]:
d=np.random.random(10)
print('the random array is:')
print(d)
d[d.argmin()] = 1
print("the min value is replaced by 1:")
print(d)

the random array is:
[0.31228094 0.73625482 0.928634   0.55737711 0.76462545 0.28792457
 0.25149598 0.14585437 0.25572253 0.31081217]
the min value is replaced by 1:
[0.31228094 0.73625482 0.928634   0.55737711 0.76462545 0.28792457
 0.25149598 1.         0.25572253 0.31081217]


#### 16. Subtract the mean of each row of a matrix (★★☆)

In [37]:
F = np.random.random((4,4))
print('Original matrix')
print(F)
print('Mean of each row of the matrix')
x = F.mean(axis = 1, keepdims = True)
print(x)
print('Substraction between the original matrix and the mean')
F_substract = F - x
print(F_substract)

Original matrix
[[0.80229441 0.98695838 0.15709951 0.98365626]
 [0.31305821 0.56441553 0.88448041 0.15695239]
 [0.02655094 0.12839155 0.38905581 0.6554021 ]
 [0.2940375  0.11307377 0.36325997 0.67840569]]
Mean of each row of the matrix
[[0.73250214]
 [0.47972663]
 [0.2998501 ]
 [0.36219423]]
Substraction between the original matrix and the mean
[[ 0.06979227  0.25445624 -0.57540263  0.25115412]
 [-0.16666842  0.0846889   0.40475377 -0.32277425]
 [-0.27329916 -0.17145855  0.08920571  0.35555201]
 [-0.06815673 -0.24912046  0.00106574  0.31621146]]


#### 17. How to get the n largest values of an array (★★★)

In [43]:
x = np.arange(100)
np.random.shuffle(x)
n=5
np.argsort(x)

array([21, 39, 79, 13, 35,  4, 87, 40, 47, 26, 31, 37, 78, 91, 69, 83, 28,
       81,  3, 17, 74, 63, 22, 19, 94, 38, 64, 12, 75, 44, 98, 61, 56, 84,
        5, 15,  7, 54, 33, 70, 18, 29, 85, 52, 45, 42, 27, 57, 76, 16, 55,
       92, 60, 50, 25, 36, 80, 58,  6, 30, 86, 90, 48, 89, 96, 20, 77, 65,
       97,  8, 14,  9, 32,  2, 34, 73, 59, 43, 23, 51, 99, 10, 62, 49, 68,
       93, 53,  1, 88, 67, 71, 11, 82, 41, 95,  0, 46, 72, 24, 66],
      dtype=int64)

#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 

In [55]:
x= np.arange(0,15).reshape(5,3)
print(x)
print("replacing of items or squaring which are larger than 4")
y=np.where(x<=4,y,x**2)
y

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
replacing of items or squaring which are larger than 4


array([[  0,   1,   2],
       [  3,   4,  25],
       [ 36,  49,  64],
       [ 81, 100, 121],
       [144, 169, 196]])

In [57]:
x= np.arange(0,15).reshape(5,3)
print(x)
print("replacing of items or squaring which are larger than 4")
y=np.where(x<=5,x,x**2)
y

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
replacing of items or squaring which are larger than 4


array([[  0,   1,   2],
       [  3,   4,   5],
       [ 36,  49,  64],
       [ 81, 100, 121],
       [144, 169, 196]])