# numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.
File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np


#### 2. Create a null vector of size 10 (★☆☆)

In [4]:
np.zeros((10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [5]:
np.array([int(x==5) for x in range(10)])

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)

In [6]:
np.arange(10,49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

0 to 8 is not possible

In [7]:
a= np.arange(0,9).reshape(3,3)
b=np.arange(0,18,2).reshape(3,3)

In [8]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

#### 7. Create a 3x3 identity matrix (★☆☆)

In [11]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 8. Create a 3x3x3 array with random values (★☆☆)

In [12]:
np.random.random(((3,3,3)))

array([[[0.25230122, 0.65051918, 0.66221423],
        [0.98807324, 0.62321118, 0.80764776],
        [0.8530244 , 0.98420309, 0.76295687]],

       [[0.91643328, 0.51948864, 0.22043253],
        [0.4638886 , 0.78004143, 0.63196272],
        [0.56692993, 0.17332274, 0.13730006]],

       [[0.49407931, 0.98413584, 0.75143384],
        [0.94823813, 0.41742891, 0.69733109],
        [0.89509503, 0.33326567, 0.77555403]]])

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
array=np.random.random((10,10))

In [14]:
array

array([[0.13656857, 0.56918064, 0.07004042, 0.70424454, 0.14530948,
        0.58201614, 0.87866031, 0.28809358, 0.1892598 , 0.34447324],
       [0.02596821, 0.81515174, 0.72523302, 0.75780379, 0.97359002,
        0.5901854 , 0.15879558, 0.40370318, 0.57980241, 0.91585291],
       [0.28394058, 0.94506755, 0.38437536, 0.10615739, 0.40676517,
        0.01160197, 0.16995804, 0.88415226, 0.59185948, 0.5826609 ],
       [0.52968077, 0.38919447, 0.44794854, 0.07860441, 0.93984066,
        0.33388357, 0.78585179, 0.21190341, 0.04417862, 0.90097763],
       [0.41005715, 0.38497126, 0.02038776, 0.07129583, 0.09457437,
        0.37442623, 0.47728715, 0.44430563, 0.75026731, 0.62640682],
       [0.14369446, 0.64961623, 0.20487462, 0.00561905, 0.38202086,
        0.59522424, 0.12102972, 0.77596105, 0.80148049, 0.33661962],
       [0.42818152, 0.94599211, 0.59078645, 0.20020173, 0.29134303,
        0.63507464, 0.75536434, 0.72122225, 0.04482011, 0.61382735],
       [0.13077769, 0.76221235, 0.5427613

In [15]:
np.min(array)

0.005619047189345583

In [16]:
np.max(array)

0.9735900165412418

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)

In [17]:
a=np.arange(30)

In [18]:
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [19]:
np.mean(a)

14.5

#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [20]:
np.diag([1, 2, 3, 4, 5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

#### 12. Normalize a 5x5 random matrix (★☆☆)


In [21]:
z=np.random.random((5,5))
print("Before normalize")
print(z)
d=(z - np.mean(z))/np.std(z)
print("After normalize")
print(d)

Before normalize
[[5.28305287e-01 6.49073661e-01 6.34260053e-01 6.94919574e-01
  9.53749546e-01]
 [9.53808456e-01 4.49012823e-01 2.52211604e-02 9.18858257e-01
  4.46557824e-01]
 [4.09205874e-02 2.82745767e-01 8.80010725e-01 8.24768060e-02
  9.16992210e-01]
 [2.17807161e-01 3.87871726e-01 6.92934872e-01 3.49752945e-03
  9.83211007e-01]
 [8.71142549e-01 2.23670217e-01 3.79551526e-04 3.23173024e-01
  7.02822560e-01]]
After normalize
[[ 0.04122901  0.40286666  0.35850771  0.54015102  1.31521041]
 [ 1.31538682 -0.19621014 -1.46524288  1.21072938 -0.20356157]
 [-1.41823137 -0.69409237  1.09440149 -1.29379239  1.20514156]
 [-0.88854928 -0.37929551  0.53420788 -1.53029371  1.40343196]
 [ 1.06784598 -0.87099252 -1.53963041 -0.57303404  0.5638163 ]]


#### 13. How to find common values between two arrays? (★☆☆)

In [22]:
print(a)
print(b)
print("the comman values are:")
np.intersect1d(a,b) 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
the comman values are:


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

#### 14. Create a random vector of size 10 and sort it (★★☆)

In [23]:
c=np.random.random(10)
print(c)
print("That was normal vector")
c.sort()
print(c)
print("This is sorted vector")

[0.47920584 0.27495788 0.17887024 0.13379544 0.74564681 0.35419932
 0.21757967 0.15093242 0.13578658 0.06860308]
That was normal vector
[0.06860308 0.13379544 0.13578658 0.15093242 0.17887024 0.21757967
 0.27495788 0.35419932 0.47920584 0.74564681]
This is sorted vector



#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [24]:
d=np.random.random(10)
print('the random array is:')
print(d)
d[d.argmax()] = 0
print("the max value is replaced by 0:")
print(d)

the random array is:
[0.88665128 0.83038803 0.8612203  0.5511823  0.38390197 0.89164696
 0.29898914 0.27210953 0.14021729 0.27230187]
the max value is replaced by 0:
[0.88665128 0.83038803 0.8612203  0.5511823  0.38390197 0.
 0.29898914 0.27210953 0.14021729 0.27230187]


In [25]:
d=np.random.random(10)
print('the random array is:')
print(d)
d[d.argmin()] = 1
print("the min value is replaced by 1:")
print(d)

the random array is:
[0.62528536 0.78823918 0.99354243 0.30703782 0.97551123 0.59345367
 0.49846451 0.56291355 0.23136822 0.68527848]
the min value is replaced by 1:
[0.62528536 0.78823918 0.99354243 0.30703782 0.97551123 0.59345367
 0.49846451 0.56291355 1.         0.68527848]


#### 16. Subtract the mean of each row of a matrix (★★☆)

In [26]:
F = np.random.random((4,4))
print('Original matrix')
print(F)
print('Mean of each row of the matrix')
x = F.mean(axis = 1, keepdims = True)
print(x)
print('Substraction between the original matrix and the mean')
F_substract = F - x
print(F_substract)

Original matrix
[[0.68238299 0.04658768 0.94561928 0.73241853]
 [0.66563974 0.9299594  0.37439228 0.67356556]
 [0.64811187 0.93644047 0.84860349 0.94367331]
 [0.00454342 0.90523572 0.70276998 0.46186188]]
Mean of each row of the matrix
[[0.60175212]
 [0.66088925]
 [0.84420729]
 [0.51860275]]
Substraction between the original matrix and the mean
[[ 0.08063087 -0.55516444  0.34386716  0.13066641]
 [ 0.00475049  0.26907015 -0.28649696  0.01267632]
 [-0.19609542  0.09223319  0.00439621  0.09946602]
 [-0.51405933  0.38663297  0.18416723 -0.05674087]]


#### 17. How to get the n largest values of an array (★★★)

In [37]:
x = np.arange(100)
np.random.shuffle(x)
print(x)

x[np.argsort(x)[-1]]

[28 78 80 36  2 11 77  1 85 99 94 30 89 70 40 26 48 34 96 79 63 20 61  8
 83 65 68 91 41 64 55  7  9 87 25 42 88 67 57 84 73 56  6 12 37 16 53 45
 13 24  4 29 32 98 59 50 72 49 33 90 76 95 82 39 93 81 43 38 51 44 31 86
 69 71 15 17  3 19 54 74 97 21 23 66 47 22 62 10 14  0 35 52  5 75 60 18
 92 27 58 46]


99

#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 

In [28]:
x= np.arange(0,15).reshape(5,3)
print(x)
print("replacing of items or squaring which are larger than 4")
y=np.where(x<=4,y,x**2)
y

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
replacing of items or squaring which are larger than 4


NameError: name 'y' is not defined

In [ ]:
x= np.arange(0,15).reshape(5,3)
print(x)
print("replacing of items or squaring which are larger than 4")
y=np.where(x<=5,x,x**2)
y